name: Deploy frontend to Google App Engine

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: scripts
    
jobs:
  build:
    name: Build Angular FE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build --prod
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.fe_gcp_credentials }}
          project_id: ${{ secrets.fe_project_id }}
          working_directory: ./client
